---
services:
    - docker

before_install:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
    - 'docker build -t "$DOCKER_USERNAME"/docker-java:1.7 .'
    - 'docker push "$DOCKER_USERNAME"/docker-java:1.7'
